fmt import path, modify control and debug scripts

diff --git a/control b/control
--- a/control
+++ b/control
@@ -1,5 +1,5 @@
 #!/bin/bash
-workspace=$(cd $(dirname $0)/; pwd)
+workspace=$(cd $(dirname $0) && pwd)
 cd $workspace
 
 module=anteye
@@ -8,49 +8,10 @@ conf=cfg.json
 pidfile=var/app.pid
 logfile=var/app.log
 
-mkdir -p var
+mkdir -p var &>/dev/null
 
-## opt
-function start() {
-    check_pid
-    running=$?
-    if [ $running -gt 0 ];then
-        echo -n "$app now is running already, pid="
-        cat $pidfile
-        return 1
-    fi
 
-    nohup ./$app -c $conf &> $logfile &
-    echo $! > $pidfile
-    echo "$app started..., pid=$!"
-}
-
-function stop() {
-    pid=`cat $pidfile`
-    kill -9 $pid
-    echo "$app stoped..."
-}
-
-function status() {
-    check_pid
-    running=$?
-    if [ $running -gt 0 ];then
-        echo -n "$app now is running, pid="
-        cat $pidfile
-    else
-        echo "$app is stoped"
-    fi
-}
-
-function show_version() {
-    ./$app -vg
-}
-
-## build
-function tailf() {
-    tail -f $logfile
-}
-
+## build & pack
 function build() {
     commit=$(git log -1 --pretty=%h)
     cat <<EOF > ./g/git.go
@@ -60,14 +21,22 @@ const (
 )
 EOF
     go build -o $app main.go
-    show_version
+    sc=$?
+    if [ $sc -ne 0 ];then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok, vsn=" 
+        ./$app -v 
+    fi
 }
 
 function pack() {
     build
     git log -1 --pretty=%h > gitversion
     version=`./$app -v`
-    tar zcvf $app-$version.tar.gz $app cfg.example.json gitversion control ./test
+    tar zcvf $app-$version.tar.gz control $app cfg.example.json gitversion ./test/debug
+    rm -f gitversion &>/dev/null
 }
 
 function packbin() {
@@ -75,11 +44,54 @@ function packbin() {
     git log -1 --pretty=%h > gitversion
     version=`./$app -v`
     tar zcvf $app-bin-$version.tar.gz $app gitversion
+    rm -f gitversion &>/dev/null
 }
 
-## help
-function help() {
-    echo "$0 build|pack|packbin|start|stop|restart|status|tail"
+## opt
+function start() {
+    check_pid
+    running=$?
+    if [ $running -gt 0 ];then
+        echo -n "started, pid="
+        cat $pidfile
+        return 1
+    fi
+
+    nohup ./$app -c $conf &> $logfile &
+    echo $! > $pidfile
+    echo "start ok, pid=$!"
+}
+
+function stop() {
+    pid=`cat $pidfile`
+    kill -9 $pid
+    echo "stoped"
+}
+
+function restart() {
+    stop
+    sleep 1
+    start
+}
+
+## other
+function status() {
+    check_pid
+    running=$?
+    if [ $running -gt 0 ];then
+        echo -n "running, pid="
+        cat $pidfile
+    else
+        echo "stoped"
+    fi
+}
+
+function version() {
+    ./$app -vg
+}
+
+function tailf() {
+    tail -f $logfile
 }
 
 ## internal
@@ -94,37 +106,45 @@ function check_pid() {
     return 0
 }
 
-## __main__
+## usage
+function usage() {
+    echo "$0 build|pack|packbin|start|stop|restart|status|tail|version"
+}
+
+## main
 action=$1
 case $action in
-    "start")
-        start
-        ;;
-    "stop")
-        stop
-        ;;
-    "restart")
-        stop && sleep 1 && start
-        ;;
-    "status")
-        status
-        ;;
-    "tail")
-        tailf
-        ;;    
-    "version")
-        show_version
-        ;;    
-    "build")
+    ## build
+    "build" )
         build
         ;;
-    "pack")
+    "pack" )
         pack
         ;;
-    "packbin")
-        packbin 
+    "packbin" )
+        packbin
         ;;
-    *)
-        help 
+    ## opt
+    "start" )
+        start
+        ;;
+    "stop" )
+        stop
+        ;;
+    "restart" )
+        restart
+        ;;
+    ## other
+    "status" )
+        status
+        ;;
+    "version" )
+        version
+        ;;
+    "tail" )
+        tailf
+        ;;
+    * )
+        usage
         ;;
 esac
